add the controlpanel adapter required to show the controlpanel in Volto
plone/plone.formwidget.recaptcha pull request #32
Opened 2022-06-08 17:00 UTC by erral

With this adapter in place, the control panel to configure the captcha will be shown in Volto too.

cc: @giuliaghisini @mamico

2022-06-10 18:06 UTC, wesleybl requested changes

2022-06-10 18:06 UTC, wesleybl commented on src/plone/formwidget/recaptcha/restapi/configure.zcml
> +    i18n_domain="plone.formwidget.hcaptcha">
None of this is necessary.

2022-06-10 18:06 UTC, wesleybl commented on src/plone/formwidget/recaptcha/restapi/controlpanel.py
> +from plone.formwidget.recaptcha.interfaces import IReCaptchaLayer
Imports are out of order.

2022-06-10 18:06 UTC, wesleybl commented on src/plone/formwidget/recaptcha/configure.zcml
> +  <include package=".restapi" zcml:condition="installed plone.restapi" />
It would be nice to have a BBB comment to make it easier to remove the condition when Plone 4.3 support is removed.

2022-06-10 18:06 UTC, wesleybl commented on src/plone/formwidget/recaptcha/restapi/controlpanel.py
> +    title = _("ReCaptcha Control Panel")
Do we need a `locales` folder in this package? I didn't see any translations of it on `plone.app.locales`.

2022-06-11 17:14 UTC, erral commented on src/plone/formwidget/recaptcha/restapi/controlpanel.py
> +    title = _("ReCaptcha Control Panel")
we have several messages here but no locales folder :/ I will add them to the PR.

2022-06-11 17:27 UTC, erral commented on src/plone/formwidget/recaptcha/restapi/controlpanel.py
> +from plone.formwidget.recaptcha.interfaces import IReCaptchaLayer
fixed

2022-06-11 17:27 UTC, erral commented on src/plone/formwidget/recaptcha/restapi/configure.zcml
> +    i18n_domain="plone.formwidget.hcaptcha">
fixed

2022-06-11 17:28 UTC, erral commented on src/plone/formwidget/recaptcha/configure.zcml
> +  <include package=".restapi" zcml:condition="installed plone.restapi" />
That's why I added the installed condition, in 4.3 plone.restapi is not installed and added the condition because of that.

2022-06-13 14:53 UTC, wesleybl commented on src/plone/formwidget/recaptcha/restapi/controlpanel.py
> +    title = _("ReCaptcha Control Panel")
@erral It is necessary to register the `locales` directory on top of `configure.zcml`:

```xml
<i18n:registerTranslations directory="locales" />
```

And please add a note in changes about it.

2022-06-13 14:56 UTC, wesleybl commented on src/plone/formwidget/recaptcha/configure.zcml
> +  <include package=".restapi" zcml:condition="installed plone.restapi" />
Yup. I'm telling you to leave a comment about this:

```suggestion
  <!-- BBB: condition needed only in Plone 4.3 -->
  <include package=".restapi" zcml:condition="installed plone.restapi" />
```

2022-06-13 18:54 UTC, erral commented on src/plone/formwidget/recaptcha/configure.zcml
> +  <include package=".restapi" zcml:condition="installed plone.restapi" />
:+1:

2022-06-13 18:54 UTC, erral commented on src/plone/formwidget/recaptcha/restapi/controlpanel.py
> +    title = _("ReCaptcha Control Panel")
:facepalm:

2022-06-13 19:24 UTC, wesleybl commented on src/plone/formwidget/recaptcha/configure.zcml
> +  <!-- BBB Needed only while we support Plone 4.3-->
```suggestion
  <!-- BBB zcml:condition needed only while we support Plone 4.3-->
```

2022-06-13 19:43 UTC, erral commented on src/plone/formwidget/recaptcha/configure.zcml
> +  <!-- BBB Needed only while we support Plone 4.3-->
👍

2022-06-13 20:52 UTC, wesleybl approved these changes
LGTM

2022-06-13 20:52 UTC, merged